name: Deploy Static Website to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Git commit SHA or tag to deploy'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specific version (or latest)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version || github.sha }}

      - name: Upload files to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        run: |
          aws s3 sync . s3://$AWS_BUCKET_NAME/ --delete \
            --exclude ".git/*" \
            --exclude ".github/*"
